{
 "title": "Apache JMeter Dashboard using Core InfluxdbBackendListenerClient",
 "description": "Monitor your Apache JMeter load test in real time with InfluxDB and Grafana.\r\nGet overall summary, errors details and particular transaction response times.",
 "tags": [ "load_test" ],
 "time": { "from": "2020-04-02T11:57:34.186Z", "to": "2020-04-02T12:42:37.013Z" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT DISTINCT(\"application\") FROM (SELECT \"text\", \"application\" FROM events)  "
   },
   { "name": "limit", "label": "Runs Limit", "query": "10" },
   {
    "name": "run",
    "label": "Test Runs",
    "query": "SELECT DISTINCT(\"testRun\") from (select \"text\", \"testRun\" from events where \"application\"=~/^$project$/) ORDER BY DESC LIMIT $limit"
   },
   {
    "name": "request",
    "label": "Request",
    "query": "SELECT distinct(\"transaction\") from (select \"min\", \"transaction\" from jmeter where \"application\"=~/^$project$/ and \"testRun\"=~/^$run$/)"
   },
   { "name": "data_source", "query": "influxdb" },
   { "name": "measurement_name", "label": "Measurement name", "query": "jmeter" },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "5"
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") AS \"count\", mean(\"avg\") AS \"average time\", mean(\"pct95.0\") AS \"95%\", mean(\"pct90.0\") AS \"90%\", mean(\"pct99.0\") AS \"99%\", mean(\"count\")/$send_interval AS \"rps\", min(\"min\"), max(\"max\"), sum(\"rb\")/sum(\"count\") as \"Recieve Bytes/request\", sum(\"sb\")/sum(\"count\") as \"Send Bytes/request\" FROM jmeter WHERE (\"application\" =~ /^$project$/) AND \"testRun\"=~/^$run$/ AND $timeFilter GROUP BY \"transaction\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\")  FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"transaction\" = 'all') AND \"testRun\" =~ /^$run$/ GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"transaction\" = 'all') AND \"testRun\" =~ /^$run$/ GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 11 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"rb\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"transaction\" = 'all') AND \"testRun\" =~ /^$run$/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 11 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"sb\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"transaction\" = 'all') AND \"testRun\" =~ /^$run$/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"transaction\" = 'all') AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval) fill(null)), (SELECT sum(\"countError\") AS \"error\" FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"transaction\" = 'all') AND \"testRun\" =~ /^$run$/  AND $timeFilter GROUP BY time($__interval) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Req / s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"count\") / $send_interval FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"transaction\" = 'all') AND \"testRun\" =~ /^$run$/  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num of Errors",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"transaction\" = 'all') AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"maxAT\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/) AND \"testRun\" =~ /^$run$/  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions Response Times (avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"avg\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/) AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions Response Times (90th pct)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct90.0\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/) AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions Response Times (95th pct)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct95.0\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/) AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions Response Times (99th pct)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct99.0\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/) AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction Send",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sb\") FROM \"$measurement_name\" WHERE  (\"application\" =~ /^$project$/) AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_transaction Recieve",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rb\") FROM \"$measurement_name\"  WHERE (\"application\" =~ /^$project$/) AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Error%",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\")/sum(\"all\") FROM (SELECT sum(\"count\") as \"all\" FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"transaction\" != 'all') AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY \"transaction\"), (SELECT sum(\"count\") AS \"error\" FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"responseCode\" !~ /^$/) AND \"testRun\" =~ /^$run$/  AND $timeFilter GROUP BY \"transaction\") GROUP BY \"transaction\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") AS \"error count\" FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"responseCode\" !~ /^$/) AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY \"transaction\",\"responseCode\",\"responseMessage\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Individual Transaction - $request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 }
  },
  {
   "title": "Total Requests - $request",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 84 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"transaction\" =~ /^$request$/ AND \"statut\" = 'all')  AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Failed Requests - $request",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 84 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"transaction\" =~ /^$request$/ AND \"statut\" = 'ko')  AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate % - $request",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 84 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM \"$measurement_name\"  WHERE (\"application\" =~ /^$project$/ AND \"transaction\" =~ /^$request$/ AND \"statut\" = 'all')  AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval) fill(null)), (SELECT sum(\"count\") AS \"error\" FROM \"$measurement_name\" WHERE (\"application\" =~ /^$project$/ AND \"transaction\" =~ /^$request$/ AND \"statut\" = 'ko')  AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval) fill(null))",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Throughput succes- $request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Req / s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"count\") / $send_interval FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$request$/ AND \"statut\" = 'ok') AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "5s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Errors - $request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num of Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE \"application\" =~ /^$application$/ AND \"transaction\" =~ /^$request$/ AND \"statut\" = 'ko'  AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Times - $request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Average",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"avg\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$request$/ AND (\"statut\" = 'ok' or \"statut\" = 'ko')) AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "Median",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"pct50.0\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$request$/ AND (\"statut\" = 'ok' or \"statut\" = 'ko')) AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "pct50.0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "90th Percentile",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"pct90.0\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$request$/ AND (\"statut\" = 'ok' or \"statut\" = 'ko')) AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct90.0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "95th Percentile",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"pct95.0\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$request$/ AND (\"statut\" = 'ok' or \"statut\" = 'ko'))  AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "99th Percentile",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"pct99.0\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$request$/ AND (\"statut\" = 'ok' or \"statut\" = 'ko'))  AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct99.0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"max\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$request$/ AND (\"statut\" = 'ok' or \"statut\" = 'ko')) AND \"testRun\" =~ /^$run$/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  }
 ]
}